version: '3'

services:

    php:
        container_name: php
        build:
                context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=Magento2"
 
    nginx:
        container_name: nginx
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        depends_on:
            - php  
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    mailhog:
        container_name: mail
        image: mailhog/mailhog:latest
        links:
            - php
        ports:
            - "1025:1025"
            - "8025:8025"
